/**
 * The Workshop — bespoke form sprite templates (op-lists).
 *
 * Authored per the ITEM_AUTHORING_TEMPLATE: each is an ordered op-list over
 * the baseline palette, recolored at compile time by the material profile
 * (`fill`/`shade` tokens). A form NOT listed here falls back to its family
 * template (`sprites.ts`), so coverage is complete from day one and this table
 * fills in over W3/W7 for the forms that deserve bespoke art.
 *
 * Style budget (authoring §5): 6–16 ops, flat fills + one shade pass + ink
 * outline, item touches the bottom margin (ground anchor). Max 3 dominant
 * color families; `ROBOT.accent` only as a small dot.
 */

import type { SpriteOpList } from '../../art/spriteOps';
import type { FormId } from './forms';

export const FORM_TEMPLATES: Partial<Record<FormId, SpriteOpList>> = {
  // bench — two posts + two plank lines + grain (authoring §5 exemplar).
  bench: {
    canvas: [256, 224],
    ops: [
      { op: 'line', x0: 64, y0: 208, x1: 70, y1: 128, width: 12, color: 'shade' },
      { op: 'line', x0: 192, y0: 208, x1: 186, y1: 128, width: 12, color: 'shade' },
      {
        op: 'path',
        points: [
          [36, 124],
          [220, 120],
          [222, 142],
          [38, 146],
        ],
        close: true,
        fill: 'fill',
        outline: 'INK.line',
        lineWidth: 5,
      },
      {
        op: 'path',
        points: [
          [36, 96],
          [220, 92],
          [222, 110],
          [38, 114],
        ],
        close: true,
        fill: 'fill',
        outline: 'INK.line',
        lineWidth: 5,
      },
      { op: 'line', x0: 70, y0: 132, x1: 90, y1: 131, width: 2, color: 'shade' },
      { op: 'line', x0: 150, y0: 132, x1: 170, y1: 131, width: 2, color: 'shade' },
    ],
  },

  // lantern — dark stem, paper cone, warm halo, accent dot (authoring §5).
  lantern: {
    canvas: [192, 288],
    ops: [
      { op: 'halo', cx: 96, cy: 120, r: 92 },
      { op: 'line', x0: 96, y0: 272, x1: 96, y1: 150, width: 7, color: 'shade' },
      {
        op: 'path',
        points: [
          [60, 150],
          [132, 150],
          [116, 92],
          [76, 92],
        ],
        close: true,
        fill: 'fill',
        outline: 'INK.line',
        lineWidth: 5,
      },
      {
        op: 'blob',
        cx: 96,
        cy: 132,
        rx: 28,
        ry: 9,
        fill: 'CLAY.pale',
        outline: 'INK.soft',
        lineWidth: 2,
      },
      {
        op: 'blob',
        cx: 96,
        cy: 110,
        rx: 6,
        ry: 6,
        fill: 'ROBOT.accent',
        outline: 'INK.soft',
        lineWidth: 2,
      },
    ],
  },

  // birdbath — pedestal + bowl + water + tiny bird (authoring §5).
  birdbath: {
    canvas: [224, 288],
    ops: [
      {
        op: 'path',
        points: [
          [96, 120],
          [88, 200],
          [76, 252],
          [148, 252],
          [136, 200],
          [128, 120],
        ],
        close: true,
        fill: 'fill',
        outline: 'INK.line',
        lineWidth: 5,
      },
      {
        op: 'blob',
        cx: 112,
        cy: 258,
        rx: 52,
        ry: 13,
        fill: 'shade',
        outline: 'INK.line',
        lineWidth: 4,
      },
      {
        op: 'blob',
        cx: 112,
        cy: 112,
        rx: 84,
        ry: 26,
        fill: 'fill',
        outline: 'INK.line',
        lineWidth: 5,
      },
      {
        op: 'blob',
        cx: 112,
        cy: 106,
        rx: 62,
        ry: 14,
        fill: 'WATER.mid',
        outline: 'INK.soft',
        lineWidth: 2,
      },
      {
        op: 'blob',
        cx: 150,
        cy: 88,
        rx: 14,
        ry: 10,
        fill: 'CLAY.blossom',
        outline: 'INK.line',
        lineWidth: 3,
      },
    ],
  },

  // post — a single upright timber with a capped top.
  post: {
    canvas: [128, 256],
    ops: [
      { op: 'line', x0: 64, y0: 244, x1: 66, y1: 60, width: 22, color: 'fill' },
      { op: 'line', x0: 64, y0: 244, x1: 66, y1: 60, width: 22, color: 'fill', jitter: 0 },
      {
        op: 'blob',
        cx: 65,
        cy: 56,
        rx: 18,
        ry: 10,
        fill: 'shade',
        outline: 'INK.line',
        lineWidth: 4,
      },
      { op: 'line', x0: 54, y0: 200, x1: 58, y1: 100, width: 2, color: 'shade' },
    ],
  },

  // beam — a horizontal timber lying on supports.
  beam: {
    canvas: [256, 128],
    ops: [
      {
        op: 'path',
        points: [
          [24, 70],
          [232, 64],
          [232, 96],
          [24, 102],
        ],
        close: true,
        fill: 'fill',
        outline: 'INK.line',
        lineWidth: 5,
      },
      { op: 'line', x0: 60, y0: 84, x1: 200, y1: 80, width: 2, color: 'shade' },
    ],
  },

  // cairn — a balanced stack of three stones.
  cairn: {
    canvas: [160, 224],
    ops: [
      {
        op: 'blob',
        cx: 80,
        cy: 190,
        rx: 46,
        ry: 28,
        fill: 'fill',
        outline: 'INK.line',
        lineWidth: 4,
      },
      {
        op: 'blob',
        cx: 80,
        cy: 138,
        rx: 34,
        ry: 22,
        fill: 'fill',
        outline: 'INK.line',
        lineWidth: 4,
      },
      {
        op: 'blob',
        cx: 80,
        cy: 96,
        rx: 22,
        ry: 16,
        fill: 'fill',
        outline: 'INK.line',
        lineWidth: 4,
      },
    ],
  },

  // brush — a short handle with a soft, splayed head.
  brush: {
    canvas: [192, 224],
    ops: [
      { op: 'line', x0: 76, y0: 212, x1: 104, y1: 112, width: 14, color: 'shade' },
      {
        op: 'path',
        points: [
          [78, 116],
          [112, 84],
          [142, 108],
          [108, 142],
        ],
        close: true,
        fill: 'fill',
        outline: 'INK.line',
        lineWidth: 5,
      },
      { op: 'line', x0: 112, y0: 92, x1: 132, y1: 70, width: 5, color: 'fill' },
      { op: 'line', x0: 120, y0: 100, x1: 146, y1: 82, width: 5, color: 'fill' },
      { op: 'line', x0: 126, y0: 110, x1: 154, y1: 98, width: 5, color: 'fill' },
      { op: 'line', x0: 86, y0: 180, x1: 94, y1: 150, width: 2, color: 'INK.soft' },
    ],
  },

  // wayfinder — a handmade compass resting on a low foot.
  wayfinder: {
    canvas: [192, 224],
    ops: [
      { op: 'line', x0: 96, y0: 212, x1: 96, y1: 176, width: 10, color: 'shade' },
      {
        op: 'blob',
        cx: 96,
        cy: 204,
        rx: 42,
        ry: 10,
        fill: 'shade',
        outline: 'INK.line',
        lineWidth: 4,
      },
      {
        op: 'blob',
        cx: 96,
        cy: 118,
        rx: 62,
        ry: 62,
        fill: 'fill',
        outline: 'INK.line',
        lineWidth: 6,
      },
      {
        op: 'blob',
        cx: 96,
        cy: 118,
        rx: 44,
        ry: 44,
        fill: 'PAPER.floor',
        outline: 'INK.soft',
        lineWidth: 3,
      },
      {
        op: 'path',
        points: [
          [96, 72],
          [108, 120],
          [96, 112],
          [84, 120],
        ],
        close: true,
        fill: 'ROBOT.accent',
        outline: 'INK.line',
        lineWidth: 3,
      },
      { op: 'line', x0: 60, y0: 118, x1: 132, y1: 118, width: 3, color: 'INK.soft' },
      {
        op: 'blob',
        cx: 96,
        cy: 118,
        rx: 6,
        ry: 6,
        fill: 'shade',
        outline: 'INK.line',
        lineWidth: 2,
      },
    ],
  },

  // field glass — twin lenses on a small shared observation stand.
  'field-glass': {
    canvas: [224, 224],
    ops: [
      { op: 'line', x0: 112, y0: 210, x1: 112, y1: 132, width: 9, color: 'shade' },
      { op: 'line', x0: 112, y0: 170, x1: 78, y1: 212, width: 6, color: 'shade' },
      { op: 'line', x0: 112, y0: 170, x1: 146, y1: 212, width: 6, color: 'shade' },
      {
        op: 'path',
        points: [
          [44, 82],
          [102, 92],
          [102, 132],
          [44, 142],
        ],
        close: true,
        fill: 'fill',
        outline: 'INK.line',
        lineWidth: 5,
      },
      {
        op: 'path',
        points: [
          [122, 92],
          [180, 82],
          [180, 142],
          [122, 132],
        ],
        close: true,
        fill: 'fill',
        outline: 'INK.line',
        lineWidth: 5,
      },
      {
        op: 'rect',
        x: 98,
        y: 104,
        w: 28,
        h: 18,
        r: 7,
        fill: 'shade',
        outline: 'INK.line',
        lineWidth: 3,
      },
      {
        op: 'blob',
        cx: 48,
        cy: 112,
        rx: 12,
        ry: 28,
        fill: 'WATER.edge',
        outline: 'INK.line',
        lineWidth: 4,
      },
      {
        op: 'blob',
        cx: 176,
        cy: 112,
        rx: 12,
        ry: 28,
        fill: 'WATER.edge',
        outline: 'INK.line',
        lineWidth: 4,
      },
    ],
  },

  // play ball — a soft wrapped ball with visible hand-tied bands.
  'play-ball': {
    canvas: [192, 224],
    ops: [
      {
        op: 'blob',
        cx: 96,
        cy: 170,
        rx: 48,
        ry: 44,
        fill: 'fill',
        outline: 'INK.line',
        lineWidth: 5,
      },
      {
        op: 'path',
        points: [
          [58, 148],
          [82, 132],
          [124, 206],
          [104, 214],
        ],
        close: true,
        fill: 'shade',
        outline: 'INK.soft',
        lineWidth: 2,
      },
      {
        op: 'path',
        points: [
          [132, 142],
          [144, 164],
          [64, 196],
          [54, 178],
        ],
        close: true,
        fill: 'shade',
        outline: 'INK.soft',
        lineWidth: 2,
      },
      { op: 'line', x0: 64, y0: 156, x1: 132, y1: 190, width: 3, color: 'INK.soft' },
      { op: 'line', x0: 72, y0: 196, x1: 128, y1: 146, width: 3, color: 'INK.soft' },
      {
        op: 'blob',
        cx: 98,
        cy: 172,
        rx: 7,
        ry: 6,
        fill: 'ROBOT.accent',
        outline: 'INK.line',
        lineWidth: 2,
      },
    ],
  },

  // cache box — a lidded trail chest with one quiet amber latch.
  'cache-box': {
    canvas: [256, 224],
    ops: [
      {
        op: 'rect',
        x: 32,
        y: 92,
        w: 192,
        h: 120,
        r: 14,
        fill: 'fill',
        outline: 'INK.line',
        lineWidth: 6,
      },
      {
        op: 'path',
        points: [
          [28, 92],
          [48, 62],
          [208, 62],
          [228, 92],
        ],
        close: true,
        fill: 'shade',
        outline: 'INK.line',
        lineWidth: 6,
      },
      { op: 'line', x0: 42, y0: 116, x1: 214, y1: 116, width: 4, color: 'INK.soft' },
      { op: 'line', x0: 72, y0: 104, x1: 72, y1: 204, width: 4, color: 'shade' },
      { op: 'line', x0: 184, y0: 104, x1: 184, y1: 204, width: 4, color: 'shade' },
      {
        op: 'rect',
        x: 116,
        y: 104,
        w: 24,
        h: 34,
        r: 5,
        fill: 'ROBOT.accent',
        outline: 'INK.line',
        lineWidth: 3,
      },
      {
        op: 'speckle',
        x: 42,
        y: 142,
        w: 168,
        h: 56,
        count: 18,
        color: 'INK.grain',
        alpha: 0.1,
        maxR: 1.2,
      },
    ],
  },

  // drinking bowl — a broad low bowl holding a calm water ellipse.
  'drinking-bowl': {
    canvas: [224, 160],
    ops: [
      {
        op: 'blob',
        cx: 112,
        cy: 122,
        rx: 86,
        ry: 34,
        fill: 'shade',
        outline: 'INK.line',
        lineWidth: 5,
      },
      {
        op: 'path',
        points: [
          [34, 114],
          [50, 146],
          [174, 146],
          [190, 114],
        ],
        close: true,
        fill: 'fill',
        outline: 'INK.line',
        lineWidth: 5,
      },
      {
        op: 'blob',
        cx: 112,
        cy: 108,
        rx: 76,
        ry: 24,
        fill: 'fill',
        outline: 'INK.line',
        lineWidth: 5,
      },
      {
        op: 'blob',
        cx: 112,
        cy: 106,
        rx: 62,
        ry: 15,
        fill: 'WATER.mid',
        outline: 'INK.soft',
        lineWidth: 2,
      },
      { op: 'line', x0: 74, y0: 108, x1: 96, y1: 104, width: 2, color: 'WATER.edge' },
      { op: 'line', x0: 120, y0: 110, x1: 148, y1: 106, width: 2, color: 'WATER.edge' },
    ],
  },

  // bug hotel — a tiny roofed cabinet with varied nesting holes.
  'bug-hotel': {
    canvas: [224, 288],
    ops: [
      {
        op: 'rect',
        x: 48,
        y: 92,
        w: 128,
        h: 180,
        r: 8,
        fill: 'fill',
        outline: 'INK.line',
        lineWidth: 6,
      },
      {
        op: 'path',
        points: [
          [34, 98],
          [112, 42],
          [190, 98],
        ],
        close: true,
        fill: 'shade',
        outline: 'INK.line',
        lineWidth: 6,
      },
      { op: 'line', x0: 112, y0: 100, x1: 112, y1: 260, width: 5, color: 'INK.soft' },
      { op: 'line', x0: 58, y0: 172, x1: 166, y1: 172, width: 5, color: 'INK.soft' },
      {
        op: 'blob',
        cx: 82,
        cy: 132,
        rx: 13,
        ry: 12,
        fill: 'shade',
        outline: 'INK.line',
        lineWidth: 3,
      },
      {
        op: 'blob',
        cx: 142,
        cy: 132,
        rx: 10,
        ry: 10,
        fill: 'shade',
        outline: 'INK.line',
        lineWidth: 3,
      },
      { op: 'line', x0: 68, y0: 210, x1: 96, y1: 238, width: 7, color: 'shade' },
      { op: 'line', x0: 128, y0: 232, x1: 154, y1: 202, width: 7, color: 'shade' },
      {
        op: 'speckle',
        x: 60,
        y: 184,
        w: 104,
        h: 66,
        count: 22,
        color: 'INK.grain',
        alpha: 0.12,
        maxR: 1.4,
      },
    ],
  },

  // raft — six lashed floats and a simple upright guide rope.
  raft: {
    canvas: [320, 192],
    ops: [
      {
        op: 'blob',
        cx: 74,
        cy: 160,
        rx: 54,
        ry: 22,
        fill: 'fill',
        outline: 'INK.line',
        lineWidth: 5,
      },
      {
        op: 'blob',
        cx: 120,
        cy: 156,
        rx: 56,
        ry: 22,
        fill: 'fill',
        outline: 'INK.line',
        lineWidth: 5,
      },
      {
        op: 'blob',
        cx: 168,
        cy: 154,
        rx: 56,
        ry: 22,
        fill: 'fill',
        outline: 'INK.line',
        lineWidth: 5,
      },
      {
        op: 'blob',
        cx: 216,
        cy: 156,
        rx: 56,
        ry: 22,
        fill: 'fill',
        outline: 'INK.line',
        lineWidth: 5,
      },
      {
        op: 'blob',
        cx: 260,
        cy: 160,
        rx: 42,
        ry: 20,
        fill: 'fill',
        outline: 'INK.line',
        lineWidth: 5,
      },
      { op: 'line', x0: 64, y0: 144, x1: 266, y1: 148, width: 7, color: 'shade' },
      { op: 'line', x0: 86, y0: 174, x1: 248, y1: 170, width: 7, color: 'shade' },
      { op: 'line', x0: 88, y0: 144, x1: 92, y1: 70, width: 7, color: 'shade' },
      {
        op: 'path',
        points: [
          [92, 72],
          [142, 96],
          [94, 116],
        ],
        close: true,
        fill: 'CLAY.pale',
        outline: 'INK.line',
        lineWidth: 4,
      },
      { op: 'line', x0: 24, y0: 184, x1: 296, y1: 184, width: 3, color: 'WATER.deep', jitter: 3 },
    ],
  },

  // --- W7 density: bespoke art for the high-traffic core forms --------------

  // bundle — a tied sheaf of stock, cord-wrapped.
  bundle: {
    canvas: [176, 128],
    ops: [
      { op: 'line', x0: 22, y0: 96, x1: 154, y1: 84, width: 7, color: 'fill' },
      { op: 'line', x0: 22, y0: 84, x1: 154, y1: 72, width: 7, color: 'fill' },
      { op: 'line', x0: 22, y0: 72, x1: 154, y1: 60, width: 7, color: 'shade' },
      { op: 'line', x0: 58, y0: 52, x1: 64, y1: 104, width: 5, color: 'SAGE.shade' },
      { op: 'line', x0: 114, y0: 50, x1: 120, y1: 102, width: 5, color: 'SAGE.shade' },
    ],
  },

  // pile — a neat heap of stones.
  pile: {
    canvas: [160, 128],
    ops: [
      {
        op: 'blob',
        cx: 56,
        cy: 96,
        rx: 30,
        ry: 20,
        fill: 'fill',
        outline: 'INK.line',
        lineWidth: 4,
      },
      {
        op: 'blob',
        cx: 104,
        cy: 98,
        rx: 32,
        ry: 19,
        fill: 'fill',
        outline: 'INK.line',
        lineWidth: 4,
      },
      {
        op: 'blob',
        cx: 80,
        cy: 64,
        rx: 26,
        ry: 17,
        fill: 'shade',
        outline: 'INK.line',
        lineWidth: 4,
      },
    ],
  },

  // cord — a coil of twisted strands.
  cord: {
    canvas: [160, 128],
    ops: [
      {
        op: 'blob',
        cx: 80,
        cy: 78,
        rx: 54,
        ry: 40,
        fill: 'fill',
        outline: 'INK.line',
        lineWidth: 5,
      },
      {
        op: 'blob',
        cx: 80,
        cy: 78,
        rx: 26,
        ry: 18,
        fill: 'shade',
        outline: 'INK.soft',
        lineWidth: 3,
      },
      { op: 'line', x0: 36, y0: 64, x1: 124, y1: 92, width: 3, color: 'shade' },
    ],
  },

  // panel — a flat boarded sheet with seams.
  panel: {
    canvas: [224, 192],
    ops: [
      {
        op: 'rect',
        x: 36,
        y: 40,
        w: 152,
        h: 132,
        r: 8,
        fill: 'fill',
        outline: 'INK.line',
        lineWidth: 5,
      },
      { op: 'line', x0: 86, y0: 46, x1: 86, y1: 166, width: 3, color: 'shade' },
      { op: 'line', x0: 138, y0: 46, x1: 138, y1: 166, width: 3, color: 'shade' },
    ],
  },

  // block — a quarried cube.
  block: {
    canvas: [192, 192],
    ops: [
      {
        op: 'rect',
        x: 40,
        y: 60,
        w: 112,
        h: 112,
        r: 6,
        fill: 'fill',
        outline: 'INK.line',
        lineWidth: 6,
      },
      {
        op: 'path',
        points: [
          [40, 60],
          [72, 32],
          [184, 32],
          [152, 60],
        ],
        close: true,
        fill: 'shade',
        outline: 'INK.line',
        lineWidth: 5,
      },
      {
        op: 'path',
        points: [
          [152, 60],
          [184, 32],
          [184, 144],
          [152, 172],
        ],
        close: true,
        fill: 'shade',
        outline: 'INK.line',
        lineWidth: 5,
      },
    ],
  },

  // ring — a woven loop.
  ring: {
    canvas: [160, 160],
    ops: [
      {
        op: 'blob',
        cx: 80,
        cy: 88,
        rx: 56,
        ry: 56,
        fill: 'fill',
        outline: 'INK.line',
        lineWidth: 6,
      },
      {
        op: 'blob',
        cx: 80,
        cy: 88,
        rx: 30,
        ry: 30,
        fill: 'PAPER.skyBottom',
        outline: 'INK.soft',
        lineWidth: 3,
      },
    ],
  },

  // vessel — an open-mouthed pot.
  vessel: {
    canvas: [192, 224],
    ops: [
      {
        op: 'path',
        points: [
          [56, 96],
          [44, 180],
          [148, 180],
          [136, 96],
        ],
        close: true,
        fill: 'fill',
        outline: 'INK.line',
        lineWidth: 5,
      },
      {
        op: 'blob',
        cx: 96,
        cy: 96,
        rx: 48,
        ry: 14,
        fill: 'shade',
        outline: 'INK.line',
        lineWidth: 5,
      },
      { op: 'line', x0: 60, y0: 132, x1: 132, y1: 132, width: 2, color: 'shade' },
    ],
  },

  // fence — two posts and two rails.
  fence: {
    canvas: [256, 176],
    ops: [
      { op: 'line', x0: 56, y0: 164, x1: 58, y1: 36, width: 12, color: 'shade' },
      { op: 'line', x0: 200, y0: 164, x1: 202, y1: 36, width: 12, color: 'shade' },
      { op: 'line', x0: 36, y0: 70, x1: 220, y1: 66, width: 11, color: 'fill' },
      { op: 'line', x0: 36, y0: 116, x1: 220, y1: 112, width: 11, color: 'fill' },
    ],
  },

  // gate — a low fence with a hinged center leaf.
  gate: {
    canvas: [256, 192],
    ops: [
      { op: 'line', x0: 44, y0: 180, x1: 46, y1: 44, width: 13, color: 'shade' },
      { op: 'line', x0: 212, y0: 180, x1: 214, y1: 44, width: 13, color: 'shade' },
      {
        op: 'rect',
        x: 80,
        y: 70,
        w: 96,
        h: 104,
        r: 6,
        fill: 'fill',
        outline: 'INK.line',
        lineWidth: 5,
      },
      { op: 'line', x0: 86, y0: 160, x1: 170, y1: 84, width: 4, color: 'shade' },
    ],
  },

  // table — a top on four legs.
  table: {
    canvas: [256, 224],
    ops: [
      { op: 'line', x0: 64, y0: 210, x1: 66, y1: 110, width: 11, color: 'shade' },
      { op: 'line', x0: 192, y0: 210, x1: 190, y1: 110, width: 11, color: 'shade' },
      {
        op: 'path',
        points: [
          [36, 96],
          [220, 92],
          [224, 120],
          [32, 124],
        ],
        close: true,
        fill: 'fill',
        outline: 'INK.line',
        lineWidth: 5,
      },
    ],
  },

  // stool — a small round seat with carved seasonal leaves.
  stool: {
    canvas: [176, 192],
    ops: [
      { op: 'line', x0: 60, y0: 176, x1: 56, y1: 110, width: 9, color: 'shade' },
      { op: 'line', x0: 116, y0: 176, x1: 120, y1: 110, width: 9, color: 'shade' },
      {
        op: 'blob',
        cx: 88,
        cy: 102,
        rx: 52,
        ry: 18,
        fill: 'fill',
        outline: 'INK.line',
        lineWidth: 5,
      },
      { op: 'grass', x: 76, baseY: 104, height: 18, lean: -8, width: 3, color: 'SAGE.deep' },
      { op: 'grass', x: 98, baseY: 104, height: 16, lean: 8, width: 3, color: 'SAGE.mid' },
      {
        op: 'blob',
        cx: 88,
        cy: 90,
        rx: 6,
        ry: 5,
        fill: 'CLAY.blossom',
        outline: 'INK.soft',
        lineWidth: 2,
      },
    ],
  },

  // lamp — a stem with a paper shade and a baked warm halo.
  lamp: {
    canvas: [192, 288],
    ops: [
      { op: 'halo', cx: 96, cy: 110, r: 84 },
      { op: 'line', x0: 96, y0: 272, x1: 96, y1: 140, width: 8, color: 'shade' },
      {
        op: 'blob',
        cx: 96,
        cy: 272,
        rx: 44,
        ry: 12,
        fill: 'shade',
        outline: 'INK.line',
        lineWidth: 4,
      },
      {
        op: 'path',
        points: [
          [60, 138],
          [132, 138],
          [116, 84],
          [76, 84],
        ],
        close: true,
        fill: 'fill',
        outline: 'INK.line',
        lineWidth: 5,
      },
      {
        op: 'blob',
        cx: 96,
        cy: 104,
        rx: 6,
        ry: 6,
        fill: 'ROBOT.accent',
        outline: 'INK.soft',
        lineWidth: 2,
      },
    ],
  },

  // planter — a low trough of earth with a sprig.
  planter: {
    canvas: [224, 176],
    ops: [
      {
        op: 'path',
        points: [
          [40, 96],
          [52, 160],
          [172, 160],
          [184, 96],
        ],
        close: true,
        fill: 'fill',
        outline: 'INK.line',
        lineWidth: 5,
      },
      {
        op: 'blob',
        cx: 112,
        cy: 98,
        rx: 70,
        ry: 14,
        fill: 'shade',
        outline: 'INK.line',
        lineWidth: 4,
      },
      { op: 'grass', x: 96, baseY: 96, height: 46, lean: -8, width: 5, color: 'SAGE.mid' },
      { op: 'grass', x: 122, baseY: 96, height: 40, lean: 10, width: 5, color: 'SAGE.deep' },
    ],
  },

  // trellis — a tall diagonal lattice.
  trellis: {
    canvas: [192, 288],
    ops: [
      { op: 'line', x0: 36, y0: 272, x1: 156, y1: 40, width: 4, color: 'fill' },
      { op: 'line', x0: 96, y0: 272, x1: 156, y1: 156, width: 4, color: 'fill' },
      { op: 'line', x0: 156, y0: 272, x1: 36, y1: 40, width: 4, color: 'fill' },
      { op: 'line', x0: 96, y0: 272, x1: 36, y1: 156, width: 4, color: 'fill' },
      {
        op: 'blob',
        cx: 96,
        cy: 120,
        rx: 12,
        ry: 10,
        fill: 'SAGE.light',
        outline: 'INK.soft',
        lineWidth: 2,
      },
    ],
  },

  // chime — a handmade crossbar with leaf plates and warm beads.
  chime: {
    canvas: [192, 288],
    ops: [
      { op: 'line', x0: 96, y0: 272, x1: 96, y1: 72, width: 8, color: 'shade' },
      { op: 'line', x0: 60, y0: 76, x1: 140, y1: 76, width: 5, color: 'shade' },
      { op: 'line', x0: 72, y0: 80, x1: 72, y1: 150, width: 3, color: 'INK.soft' },
      { op: 'line', x0: 96, y0: 80, x1: 96, y1: 168, width: 3, color: 'INK.soft' },
      { op: 'line', x0: 120, y0: 80, x1: 120, y1: 144, width: 3, color: 'INK.soft' },
      {
        op: 'blob',
        cx: 96,
        cy: 178,
        rx: 9,
        ry: 12,
        fill: 'fill',
        outline: 'INK.line',
        lineWidth: 3,
      },
      {
        op: 'blob',
        cx: 120,
        cy: 152,
        rx: 8,
        ry: 6,
        fill: 'ROBOT.accent',
        outline: 'INK.soft',
        lineWidth: 2,
      },
      {
        op: 'path',
        points: [
          [62, 148],
          [72, 138],
          [82, 150],
          [72, 166],
        ],
        close: true,
        fill: 'SAGE.mid',
        outline: 'INK.soft',
        lineWidth: 2,
      },
      {
        op: 'path',
        points: [
          [84, 174],
          [96, 164],
          [108, 176],
          [96, 190],
        ],
        close: true,
        fill: 'SAGE.light',
        outline: 'INK.soft',
        lineWidth: 2,
      },
    ],
  },

  // mat — a flat woven rectangle (ground decal read).
  mat: {
    canvas: [256, 160],
    ops: [
      {
        op: 'blob',
        cx: 128,
        cy: 96,
        rx: 104,
        ry: 52,
        fill: 'fill',
        outline: 'INK.line',
        lineWidth: 5,
        irregularity: 0.05,
      },
      {
        op: 'blob',
        cx: 128,
        cy: 96,
        rx: 80,
        ry: 38,
        fill: 'shade',
        outline: 'INK.soft',
        lineWidth: 2,
        irregularity: 0.05,
      },
    ],
  },

  // sign — a board on a post with carved ticks.
  sign: {
    canvas: [224, 288],
    ops: [
      { op: 'line', x0: 112, y0: 276, x1: 112, y1: 120, width: 11, color: 'shade' },
      {
        op: 'rect',
        x: 44,
        y: 70,
        w: 136,
        h: 64,
        r: 8,
        fill: 'fill',
        outline: 'INK.line',
        lineWidth: 5,
      },
      { op: 'line', x0: 64, y0: 96, x1: 160, y1: 94, width: 4, color: 'INK.soft' },
      { op: 'line', x0: 64, y0: 114, x1: 132, y1: 112, width: 4, color: 'INK.soft' },
    ],
  },

  // basket — a woven open carrier.
  basket: {
    canvas: [192, 192],
    ops: [
      {
        op: 'path',
        points: [
          [44, 92],
          [56, 170],
          [136, 170],
          [148, 92],
        ],
        close: true,
        fill: 'fill',
        outline: 'INK.line',
        lineWidth: 5,
      },
      {
        op: 'blob',
        cx: 96,
        cy: 92,
        rx: 56,
        ry: 14,
        fill: 'shade',
        outline: 'INK.line',
        lineWidth: 4,
      },
      { op: 'line', x0: 48, y0: 88, x1: 144, y1: 88, width: 4, color: 'shade' },
      { op: 'line', x0: 56, y0: 60, x1: 136, y1: 60, width: 5, color: 'fill', jitter: 5 },
    ],
  },

  // sprout pot — a round clay vessel with one hopeful living shoot.
  'sprout-pot': {
    canvas: [176, 192],
    ops: [
      {
        op: 'path',
        points: [
          [44, 92],
          [58, 176],
          [118, 176],
          [132, 92],
        ],
        close: true,
        fill: 'fill',
        outline: 'INK.line',
        lineWidth: 5,
      },
      {
        op: 'blob',
        cx: 88,
        cy: 92,
        rx: 48,
        ry: 14,
        fill: 'shade',
        outline: 'INK.line',
        lineWidth: 4,
      },
      { op: 'line', x0: 88, y0: 88, x1: 88, y1: 42, width: 5, color: 'SAGE.deep' },
      {
        op: 'path',
        points: [
          [86, 62],
          [58, 46],
          [64, 74],
        ],
        close: true,
        fill: 'SAGE.light',
        outline: 'INK.soft',
        lineWidth: 2,
      },
      {
        op: 'path',
        points: [
          [90, 52],
          [118, 36],
          [112, 66],
        ],
        close: true,
        fill: 'SAGE.mid',
        outline: 'INK.soft',
        lineWidth: 2,
      },
      {
        op: 'blob',
        cx: 88,
        cy: 36,
        rx: 6,
        ry: 6,
        fill: 'ROBOT.accent',
        outline: 'INK.soft',
        lineWidth: 2,
      },
    ],
  },

  // mailbox — a rounded wooden box, little door, leaf carving, and post.
  mailbox: {
    canvas: [208, 256],
    ops: [
      { op: 'line', x0: 104, y0: 244, x1: 104, y1: 142, width: 13, color: 'shade' },
      {
        op: 'blob',
        cx: 104,
        cy: 244,
        rx: 38,
        ry: 9,
        fill: 'shade',
        outline: 'INK.line',
        lineWidth: 3,
      },
      {
        op: 'rect',
        x: 40,
        y: 76,
        w: 128,
        h: 82,
        r: 22,
        fill: 'fill',
        outline: 'INK.line',
        lineWidth: 5,
      },
      {
        op: 'path',
        points: [
          [40, 98],
          [66, 58],
          [142, 58],
          [168, 98],
        ],
        close: true,
        fill: 'shade',
        outline: 'INK.line',
        lineWidth: 5,
      },
      {
        op: 'rect',
        x: 64,
        y: 100,
        w: 78,
        h: 42,
        r: 8,
        fill: 'CLAY.pale',
        outline: 'INK.soft',
        lineWidth: 3,
      },
      {
        op: 'blob',
        cx: 130,
        cy: 121,
        rx: 5,
        ry: 5,
        fill: 'ROBOT.accent',
        outline: 'INK.soft',
        lineWidth: 2,
      },
      {
        op: 'path',
        points: [
          [78, 116],
          [92, 104],
          [100, 120],
          [88, 130],
        ],
        close: true,
        fill: 'SAGE.mid',
        outline: 'INK.soft',
        lineWidth: 2,
      },
      {
        op: 'speckle',
        x: 46,
        y: 66,
        w: 116,
        h: 84,
        count: 12,
        color: 'SAGE.deep',
        alpha: 0.16,
        maxR: 2,
      },
    ],
  },

  // mushroom lamp — broad cap, pale stem, and a quiet amber light beneath.
  'mushroom-lamp': {
    canvas: [208, 240],
    ops: [
      { op: 'halo', cx: 104, cy: 102, r: 76 },
      {
        op: 'path',
        points: [
          [78, 116],
          [72, 222],
          [136, 222],
          [130, 116],
        ],
        close: true,
        fill: 'CLAY.pale',
        outline: 'INK.line',
        lineWidth: 5,
      },
      {
        op: 'blob',
        cx: 104,
        cy: 222,
        rx: 48,
        ry: 11,
        fill: 'shade',
        outline: 'INK.line',
        lineWidth: 4,
      },
      {
        op: 'path',
        points: [
          [30, 112],
          [50, 58],
          [104, 34],
          [158, 58],
          [178, 112],
        ],
        close: true,
        fill: 'fill',
        outline: 'INK.line',
        lineWidth: 6,
      },
      {
        op: 'blob',
        cx: 104,
        cy: 110,
        rx: 70,
        ry: 15,
        fill: 'CLAY.pale',
        outline: 'INK.soft',
        lineWidth: 3,
      },
      {
        op: 'blob',
        cx: 104,
        cy: 102,
        rx: 7,
        ry: 7,
        fill: 'ROBOT.accent',
        outline: 'INK.soft',
        lineWidth: 2,
      },
      {
        op: 'blob',
        cx: 76,
        cy: 70,
        rx: 7,
        ry: 5,
        fill: 'CLAY.pale',
        outline: 'INK.soft',
        lineWidth: 2,
      },
      {
        op: 'blob',
        cx: 132,
        cy: 62,
        rx: 6,
        ry: 5,
        fill: 'CLAY.pale',
        outline: 'INK.soft',
        lineWidth: 2,
      },
    ],
  },

  // pet bed — a low woven nest with a folded soft blanket.
  'pet-bed': {
    canvas: [240, 160],
    ops: [
      {
        op: 'blob',
        cx: 120,
        cy: 112,
        rx: 102,
        ry: 42,
        fill: 'fill',
        outline: 'INK.line',
        lineWidth: 5,
        irregularity: 0.05,
      },
      {
        op: 'blob',
        cx: 120,
        cy: 106,
        rx: 76,
        ry: 28,
        fill: 'CLAY.pale',
        outline: 'INK.soft',
        lineWidth: 3,
        irregularity: 0.05,
      },
      {
        op: 'path',
        points: [
          [70, 98],
          [126, 86],
          [170, 116],
          [104, 132],
        ],
        close: true,
        fill: 'SAGE.light',
        outline: 'INK.soft',
        lineWidth: 3,
      },
      { op: 'line', x0: 88, y0: 104, x1: 148, y1: 116, width: 3, color: 'SAGE.deep' },
      { op: 'line', x0: 38, y0: 118, x1: 68, y1: 128, width: 3, color: 'shade' },
      { op: 'line', x0: 172, y0: 126, x1: 202, y1: 116, width: 3, color: 'shade' },
    ],
  },

  // food bowl — a shallow ceramic dish with a paw-like stamped mark.
  'food-bowl': {
    canvas: [192, 128],
    ops: [
      {
        op: 'path',
        points: [
          [34, 54],
          [50, 116],
          [142, 116],
          [158, 54],
        ],
        close: true,
        fill: 'fill',
        outline: 'INK.line',
        lineWidth: 5,
      },
      {
        op: 'blob',
        cx: 96,
        cy: 54,
        rx: 64,
        ry: 17,
        fill: 'CLAY.pale',
        outline: 'INK.line',
        lineWidth: 4,
      },
      {
        op: 'blob',
        cx: 96,
        cy: 58,
        rx: 42,
        ry: 10,
        fill: 'shade',
        outline: 'INK.soft',
        lineWidth: 2,
      },
      {
        op: 'blob',
        cx: 96,
        cy: 88,
        rx: 8,
        ry: 7,
        fill: 'ROBOT.accent',
        outline: 'INK.soft',
        lineWidth: 2,
      },
      {
        op: 'blob',
        cx: 84,
        cy: 78,
        rx: 4,
        ry: 4,
        fill: 'ROBOT.accent',
        outline: 'INK.soft',
        lineWidth: 1,
      },
      {
        op: 'blob',
        cx: 108,
        cy: 78,
        rx: 4,
        ry: 4,
        fill: 'ROBOT.accent',
        outline: 'INK.soft',
        lineWidth: 1,
      },
    ],
  },

  // garden lantern — a squat stone tower with a warm open window.
  'garden-lantern': {
    canvas: [192, 256],
    ops: [
      { op: 'halo', cx: 96, cy: 112, r: 68 },
      {
        op: 'blob',
        cx: 96,
        cy: 240,
        rx: 54,
        ry: 12,
        fill: 'shade',
        outline: 'INK.line',
        lineWidth: 4,
      },
      {
        op: 'path',
        points: [
          [72, 226],
          [80, 142],
          [112, 142],
          [120, 226],
        ],
        close: true,
        fill: 'fill',
        outline: 'INK.line',
        lineWidth: 5,
      },
      {
        op: 'rect',
        x: 54,
        y: 80,
        w: 84,
        h: 72,
        r: 10,
        fill: 'fill',
        outline: 'INK.line',
        lineWidth: 5,
      },
      {
        op: 'rect',
        x: 72,
        y: 96,
        w: 48,
        h: 38,
        r: 8,
        fill: 'CLAY.pale',
        outline: 'INK.soft',
        lineWidth: 3,
      },
      {
        op: 'blob',
        cx: 96,
        cy: 114,
        rx: 7,
        ry: 7,
        fill: 'ROBOT.accent',
        outline: 'INK.soft',
        lineWidth: 2,
      },
      {
        op: 'path',
        points: [
          [36, 82],
          [96, 46],
          [156, 82],
          [142, 94],
          [50, 94],
        ],
        close: true,
        fill: 'shade',
        outline: 'INK.line',
        lineWidth: 5,
      },
    ],
  },

  // seed chest — an open compartment box with quiet glowing seed points.
  'seed-chest': {
    canvas: [224, 184],
    ops: [
      {
        op: 'rect',
        x: 34,
        y: 86,
        w: 156,
        h: 84,
        r: 10,
        fill: 'fill',
        outline: 'INK.line',
        lineWidth: 5,
      },
      {
        op: 'path',
        points: [
          [40, 86],
          [58, 40],
          [178, 40],
          [188, 86],
        ],
        close: true,
        fill: 'shade',
        outline: 'INK.line',
        lineWidth: 5,
      },
      {
        op: 'rect',
        x: 52,
        y: 100,
        w: 52,
        h: 42,
        r: 6,
        fill: 'CLAY.pale',
        outline: 'INK.soft',
        lineWidth: 3,
      },
      {
        op: 'rect',
        x: 120,
        y: 100,
        w: 52,
        h: 42,
        r: 6,
        fill: 'CLAY.pale',
        outline: 'INK.soft',
        lineWidth: 3,
      },
      {
        op: 'blob',
        cx: 76,
        cy: 120,
        rx: 6,
        ry: 6,
        fill: 'ROBOT.accent',
        outline: 'INK.soft',
        lineWidth: 2,
      },
      {
        op: 'blob',
        cx: 144,
        cy: 118,
        rx: 5,
        ry: 5,
        fill: 'ROBOT.accent',
        outline: 'INK.soft',
        lineWidth: 2,
      },
      { op: 'grass', x: 154, baseY: 132, height: 24, lean: 8, width: 3, color: 'SAGE.mid' },
    ],
  },

  // repair toy — a worn little robot with one visibly mended foot.
  'repair-toy': {
    canvas: [176, 208],
    ops: [
      {
        op: 'rect',
        x: 50,
        y: 74,
        w: 76,
        h: 74,
        r: 18,
        fill: 'ROBOT.shell',
        outline: 'INK.line',
        lineWidth: 5,
      },
      {
        op: 'rect',
        x: 62,
        y: 88,
        w: 52,
        h: 26,
        r: 10,
        fill: 'ROBOT.visor',
        outline: 'INK.soft',
        lineWidth: 3,
      },
      {
        op: 'blob',
        cx: 78,
        cy: 100,
        rx: 4,
        ry: 4,
        fill: 'ROBOT.accent',
        outline: 'INK.soft',
        lineWidth: 1,
      },
      {
        op: 'blob',
        cx: 98,
        cy: 100,
        rx: 4,
        ry: 4,
        fill: 'ROBOT.accent',
        outline: 'INK.soft',
        lineWidth: 1,
      },
      { op: 'line', x0: 58, y0: 140, x1: 48, y1: 194, width: 10, color: 'ROBOT.dark' },
      { op: 'line', x0: 116, y0: 140, x1: 128, y1: 194, width: 10, color: 'ROBOT.dark' },
      {
        op: 'blob',
        cx: 44,
        cy: 196,
        rx: 24,
        ry: 8,
        fill: 'fill',
        outline: 'INK.line',
        lineWidth: 3,
      },
      {
        op: 'blob',
        cx: 132,
        cy: 196,
        rx: 20,
        ry: 8,
        fill: 'ROBOT.shellShade',
        outline: 'INK.line',
        lineWidth: 3,
      },
      { op: 'line', x0: 42, y0: 184, x1: 54, y1: 198, width: 3, color: 'CLAY.blossom' },
      { op: 'line', x0: 54, y0: 184, x1: 42, y1: 198, width: 3, color: 'CLAY.blossom' },
    ],
  },

  // shelter — a gabled kennel in robot cream.
  shelter: {
    canvas: [288, 256],
    ops: [
      {
        op: 'rect',
        x: 56,
        y: 120,
        w: 176,
        h: 116,
        r: 12,
        fill: 'fill',
        outline: 'INK.line',
        lineWidth: 6,
      },
      {
        op: 'path',
        points: [
          [36, 126],
          [144, 48],
          [252, 126],
        ],
        close: true,
        fill: 'shade',
        outline: 'INK.line',
        lineWidth: 6,
      },
      {
        op: 'path',
        points: [
          [112, 236],
          [112, 168],
          [144, 140],
          [176, 168],
          [176, 236],
        ],
        close: true,
        fill: 'ROBOT.visor',
        outline: 'INK.line',
        lineWidth: 5,
      },
      {
        op: 'blob',
        cx: 144,
        cy: 128,
        rx: 7,
        ry: 7,
        fill: 'ROBOT.accent',
        outline: 'INK.line',
        lineWidth: 2,
      },
    ],
  },

  // archway — two posts and a gentle arch with blossoms.
  archway: {
    canvas: [288, 320],
    ops: [
      { op: 'line', x0: 64, y0: 304, x1: 64, y1: 120, width: 13, color: 'fill' },
      { op: 'line', x0: 224, y0: 304, x1: 224, y1: 120, width: 13, color: 'fill' },
      {
        op: 'path',
        points: [
          [52, 124],
          [144, 36],
          [236, 124],
        ],
        outline: 'fill',
        lineWidth: 14,
      },
      {
        op: 'blob',
        cx: 100,
        cy: 80,
        rx: 11,
        ry: 9,
        fill: 'CLAY.blossom',
        outline: 'INK.soft',
        lineWidth: 2,
      },
      {
        op: 'blob',
        cx: 188,
        cy: 80,
        rx: 11,
        ry: 9,
        fill: 'CLAY.blossom',
        outline: 'INK.soft',
        lineWidth: 2,
      },
    ],
  },

  // pergola — posts under a flat slatted roof.
  pergola: {
    canvas: [288, 256],
    ops: [
      { op: 'line', x0: 56, y0: 240, x1: 56, y1: 96, width: 12, color: 'fill' },
      { op: 'line', x0: 232, y0: 240, x1: 232, y1: 96, width: 12, color: 'fill' },
      {
        op: 'rect',
        x: 32,
        y: 70,
        w: 224,
        h: 18,
        r: 4,
        fill: 'shade',
        outline: 'INK.line',
        lineWidth: 4,
      },
      { op: 'line', x0: 70, y0: 64, x1: 70, y1: 92, width: 5, color: 'fill' },
      { op: 'line', x0: 120, y0: 64, x1: 120, y1: 92, width: 5, color: 'fill' },
      { op: 'line', x0: 170, y0: 64, x1: 170, y1: 92, width: 5, color: 'fill' },
      { op: 'line', x0: 220, y0: 64, x1: 220, y1: 92, width: 5, color: 'fill' },
    ],
  },

  // well — a low stone ring with a little roof.
  well: {
    canvas: [224, 288],
    ops: [
      {
        op: 'path',
        points: [
          [56, 160],
          [64, 248],
          [160, 248],
          [168, 160],
        ],
        close: true,
        fill: 'fill',
        outline: 'INK.line',
        lineWidth: 6,
      },
      {
        op: 'blob',
        cx: 112,
        cy: 160,
        rx: 60,
        ry: 18,
        fill: 'ROBOT.visor',
        outline: 'INK.line',
        lineWidth: 5,
      },
      { op: 'line', x0: 64, y0: 156, x1: 60, y1: 64, width: 7, color: 'shade' },
      { op: 'line', x0: 160, y0: 156, x1: 164, y1: 64, width: 7, color: 'shade' },
      {
        op: 'path',
        points: [
          [44, 70],
          [112, 28],
          [180, 70],
        ],
        close: true,
        fill: 'shade',
        outline: 'INK.line',
        lineWidth: 5,
      },
    ],
  },

  // shrine — a small stone niche with an upright marker.
  shrine: {
    canvas: [224, 288],
    ops: [
      {
        op: 'path',
        points: [
          [52, 130],
          [52, 256],
          [172, 256],
          [172, 130],
          [112, 88],
        ],
        close: true,
        fill: 'fill',
        outline: 'INK.line',
        lineWidth: 6,
      },
      {
        op: 'rect',
        x: 92,
        y: 150,
        w: 40,
        h: 96,
        r: 8,
        fill: 'ROBOT.visor',
        outline: 'INK.line',
        lineWidth: 4,
      },
      {
        op: 'blob',
        cx: 112,
        cy: 176,
        rx: 8,
        ry: 8,
        fill: 'ROBOT.accent',
        outline: 'INK.soft',
        lineWidth: 2,
      },
    ],
  },

  // cold-frame — a low glazed box over earth.
  'cold-frame': {
    canvas: [256, 192],
    ops: [
      {
        op: 'rect',
        x: 40,
        y: 120,
        w: 176,
        h: 56,
        r: 6,
        fill: 'shade',
        outline: 'INK.line',
        lineWidth: 5,
      },
      {
        op: 'path',
        points: [
          [40, 120],
          [76, 76],
          [216, 76],
          [216, 120],
        ],
        close: true,
        fill: 'WATER.edge',
        outline: 'INK.line',
        lineWidth: 5,
      },
      { op: 'line', x0: 110, y0: 80, x1: 92, y1: 118, width: 3, color: 'INK.soft' },
      { op: 'line', x0: 160, y0: 80, x1: 150, y1: 118, width: 3, color: 'INK.soft' },
    ],
  },

  // campfire — stone ring, crossed logs, a quiet flame + warm halo.
  campfire: {
    canvas: [224, 192],
    ops: [
      { op: 'halo', cx: 112, cy: 120, r: 88 },
      { op: 'line', x0: 56, y0: 168, x1: 168, y1: 144, width: 12, color: 'shade' },
      { op: 'line', x0: 60, y0: 144, x1: 164, y1: 170, width: 12, color: 'fill' },
      {
        op: 'path',
        points: [
          [112, 64],
          [138, 116],
          [112, 148],
          [86, 116],
        ],
        close: true,
        fill: 'ROBOT.accent',
        outline: 'INK.line',
        lineWidth: 4,
      },
      {
        op: 'blob',
        cx: 56,
        cy: 174,
        rx: 14,
        ry: 10,
        fill: 'CLAY.pale',
        outline: 'INK.line',
        lineWidth: 3,
      },
      {
        op: 'blob',
        cx: 168,
        cy: 174,
        rx: 14,
        ry: 10,
        fill: 'CLAY.pale',
        outline: 'INK.line',
        lineWidth: 3,
      },
    ],
  },

  // garland — a sweeping arc of blossoms (worn read).
  garland: {
    canvas: [224, 128],
    ops: [
      {
        op: 'line',
        x0: 24,
        y0: 48,
        x1: 200,
        y1: 48,
        width: 6,
        color: 'SAGE.shade',
        jitter: 10,
        segments: 8,
      },
      {
        op: 'blob',
        cx: 56,
        cy: 78,
        rx: 12,
        ry: 10,
        fill: 'fill',
        outline: 'INK.soft',
        lineWidth: 2,
      },
      {
        op: 'blob',
        cx: 96,
        cy: 92,
        rx: 12,
        ry: 10,
        fill: 'fill',
        outline: 'INK.soft',
        lineWidth: 2,
      },
      {
        op: 'blob',
        cx: 136,
        cy: 92,
        rx: 12,
        ry: 10,
        fill: 'fill',
        outline: 'INK.soft',
        lineWidth: 2,
      },
      {
        op: 'blob',
        cx: 176,
        cy: 78,
        rx: 12,
        ry: 10,
        fill: 'fill',
        outline: 'INK.soft',
        lineWidth: 2,
      },
    ],
  },

  // stick — the fetch toy: a sturdy forked branch with a grip wrap.
  stick: {
    canvas: [192, 128],
    ops: [
      { op: 'line', x0: 24, y0: 84, x1: 168, y1: 56, width: 10, color: 'fill' },
      { op: 'line', x0: 120, y0: 64, x1: 156, y1: 30, width: 7, color: 'fill' },
      { op: 'line', x0: 44, y0: 74, x1: 52, y1: 92, width: 4, color: 'shade' },
      { op: 'line', x0: 52, y0: 72, x1: 60, y1: 90, width: 4, color: 'shade' },
    ],
  },

  // axe — a wedge head clamped on a handle (tool, rides in the gripper).
  axe: {
    canvas: [160, 224],
    ops: [
      { op: 'line', x0: 84, y0: 212, x1: 76, y1: 60, width: 11, color: 'shade' },
      {
        op: 'path',
        points: [
          [60, 56],
          [120, 40],
          [128, 92],
          [70, 96],
        ],
        close: true,
        fill: 'fill',
        outline: 'INK.line',
        lineWidth: 5,
      },
      { op: 'line', x0: 80, y0: 70, x1: 76, y1: 180, width: 3, color: 'INK.soft' },
    ],
  },

  // pickaxe — a double-pointed head crossing a handle.
  pickaxe: {
    canvas: [192, 224],
    ops: [
      { op: 'line', x0: 96, y0: 212, x1: 96, y1: 70, width: 11, color: 'shade' },
      {
        op: 'path',
        points: [
          [28, 92],
          [96, 60],
          [164, 92],
          [96, 80],
        ],
        close: true,
        fill: 'fill',
        outline: 'INK.line',
        lineWidth: 5,
      },
    ],
  },

  // shears — two hinged blades.
  shears: {
    canvas: [160, 224],
    ops: [
      { op: 'line', x0: 72, y0: 212, x1: 64, y1: 120, width: 6, color: 'shade' },
      { op: 'line', x0: 88, y0: 212, x1: 96, y1: 120, width: 6, color: 'shade' },
      {
        op: 'path',
        points: [
          [64, 120],
          [40, 48],
          [60, 44],
          [80, 112],
        ],
        close: true,
        fill: 'fill',
        outline: 'INK.line',
        lineWidth: 4,
      },
      {
        op: 'path',
        points: [
          [96, 120],
          [120, 48],
          [100, 44],
          [80, 112],
        ],
        close: true,
        fill: 'fill',
        outline: 'INK.line',
        lineWidth: 4,
      },
      {
        op: 'blob',
        cx: 80,
        cy: 116,
        rx: 6,
        ry: 6,
        fill: 'ROBOT.accent',
        outline: 'INK.line',
        lineWidth: 2,
      },
    ],
  },

  // scoop — a cupped head on a handle.
  scoop: {
    canvas: [160, 224],
    ops: [
      { op: 'line', x0: 80, y0: 212, x1: 80, y1: 96, width: 10, color: 'shade' },
      {
        op: 'path',
        points: [
          [44, 92],
          [116, 92],
          [104, 48],
          [56, 48],
        ],
        close: true,
        fill: 'fill',
        outline: 'INK.line',
        lineWidth: 5,
      },
    ],
  },
};
