/**
 * Identity-first Workshop form catalog.
 *
 * Every id below names a distinct object with its own function and silhouette.
 * Rarity, material, size, and finish are metadata/variants; they never create
 * fake forms such as "painted chair" or "ancient chair".
 */

import type {
  Form,
  FormFamily,
  FormIdentity,
  FormUse,
  IdentitySilhouette,
  ItemRarity,
} from './forms';

interface IdentityGroup {
  readonly key: string;
  readonly family: FormFamily;
  readonly silhouette: IdentitySilhouette;
  readonly proportions: FormIdentity['proportions'];
  readonly cue: string;
  readonly accepts: Form['accepts'];
  readonly use: FormUse;
  readonly tier: Form['tier'];
  readonly ids: readonly string[];
}

const GROUPS = [
  group(
    'masonry-parts',
    'component',
    'slab',
    'low-wide',
    'load-bearing cut-stone edges',
    ['stone'],
    'component',
    2,
    [
      'foundation-slab',
      'cornerstone',
      'capstone',
      'keystone',
      'sill-stone',
      'threshold-stone',
      'coping-stone',
      'stepping-slab',
      'drainage-stone',
      'hearth-slab',
    ],
  ),
  group(
    'timber-parts',
    'component',
    'beam',
    'long-thin',
    'structural grain and load direction',
    ['wood'],
    'component',
    2,
    [
      'joist',
      'rafter',
      'roof-truss',
      'knee-brace',
      'corbel',
      'lintel',
      'sill-beam',
      'crossbeam',
      'trestle-frame',
      'ladder-rung',
    ],
  ),
  group(
    'open-frames',
    'component',
    'frame',
    'upright',
    'an unmistakable framed opening',
    ['wood', 'stone'],
    'component',
    2,
    [
      'window-frame',
      'door-jamb',
      'mullion',
      'transom-bar',
      'shutter-frame',
      'lattice-frame',
      'screen-frame',
      'hatch-frame',
      'vent-frame',
      'skylight-frame',
    ],
  ),
  group(
    'joinery',
    'component',
    'joint',
    'compact',
    'interlocking faces that explain assembly',
    ['wood', 'stone', 'found'],
    'component',
    1,
    [
      'dowel',
      'peg',
      'wedge',
      'shim',
      'mortise-block',
      'tenon-block',
      'scarf-joint',
      'lap-joint',
      'hinge-leaf',
      'latch-plate',
    ],
  ),
  group(
    'mechanisms',
    'component',
    'mechanism',
    'compact',
    'visible rotational or reciprocating motion',
    ['wood', 'stone', 'found'],
    'component',
    3,
    [
      'axle',
      'pulley',
      'sprocket',
      'hand-crank',
      'flywheel',
      'gear-train',
      'ratchet',
      'spring-coil',
      'counterweight',
      'bearing-block',
    ],
  ),
  group(
    'conduits',
    'component',
    'conduit',
    'long-thin',
    'a clear inlet-to-outlet path',
    ['stone', 'found'],
    'component',
    2,
    [
      'pipe',
      'pipe-elbow',
      'pipe-tee',
      'valve-body',
      'spout',
      'nozzle',
      'funnel',
      'chute',
      'duct',
      'vent-cover',
    ],
  ),
  group(
    'surface-parts',
    'component',
    'panel',
    'flat',
    'surface rhythm and edge treatment',
    ['wood', 'stone', 'plant'],
    'component',
    1,
    [
      'floorboard',
      'wallboard',
      'roof-shingle',
      'clay-tile',
      'mosaic-tile',
      'woven-panel',
      'reed-screen',
      'felt-pad',
      'cork-sheet',
      'pegboard',
    ],
  ),
  group(
    'bindings',
    'component',
    'binding',
    'long-thin',
    'loops, tension, and fastening points',
    ['wood', 'plant', 'found'],
    'component',
    1,
    [
      'rope-ladder',
      'chain-link',
      'cable-loop',
      'carry-strap',
      'buckle',
      'clasp',
      'utility-hook',
      'eyelet',
      'spool',
      'reel',
    ],
  ),

  group(
    'compact-seating',
    'furnishing',
    'seat',
    'compact',
    'a distinct sitting posture',
    ['wood', 'stone', 'plant'],
    'place',
    1,
    [
      'rocking-chair',
      'kneeling-chair',
      'deck-chair',
      'sling-chair',
      'saddle-stool',
      'tripod-stool',
      'window-seat',
      'reading-chair',
      'floor-cushion',
      'meditation-seat',
    ],
  ),
  group(
    'shared-seating',
    'furnishing',
    'seat-wide',
    'low-wide',
    'space for a particular shared rest ritual',
    ['wood', 'stone', 'plant'],
    'place',
    2,
    [
      'porch-swing',
      'hanging-seat',
      'conversation-seat',
      'corner-seat',
      'storage-bench',
      'step-stool',
      'drafting-stool',
      'piano-stool',
      'garden-seat',
      'hearth-seat',
      'day-couch',
      'chaise',
      'settle',
      'ottoman',
      'footrest',
    ],
  ),
  group(
    'work-surfaces',
    'furnishing',
    'table',
    'low-wide',
    'a purpose-specific work surface and support layout',
    ['wood', 'stone'],
    'place',
    2,
    [
      'writing-desk',
      'rolltop-desk',
      'drafting-table',
      'tea-table',
      'side-table',
      'console-table',
      'nesting-table',
      'worktable',
      'potting-table',
      'wash-table',
      'breakfast-bar',
      'island-counter',
      'folding-counter',
      'map-table',
      'game-table',
      'display-plinth',
      'plant-stand',
      'lectern',
      'tray-stand',
      'sewing-table',
    ],
  ),
  group(
    'storage-furniture',
    'furnishing',
    'storage',
    'upright',
    'doors, drawers, or open storage that reveal use',
    ['wood', 'stone', 'plant'],
    'place',
    2,
    [
      'wardrobe',
      'armoire',
      'dresser',
      'nightstand',
      'sideboard',
      'hutch',
      'pantry-cupboard',
      'linen-chest',
      'blanket-box',
      'tool-chest',
      'apothecary-cabinet',
      'map-cabinet',
      'specimen-cabinet',
      'shoe-rack',
      'coat-rack',
      'umbrella-stand',
      'wall-shelf',
      'corner-shelf',
      'ladder-shelf',
      'cubby-unit',
      'drawer-unit',
      'crate-stack',
      'bottle-rack',
      'plate-rack',
      'basket-tower',
    ],
  ),
  group(
    'lighting',
    'furnishing',
    'light',
    'upright',
    'a believable light source, shade, and support',
    ['wood', 'stone', 'plant', 'found'],
    'place',
    2,
    [
      'floor-lamp',
      'desk-lamp',
      'wall-sconce',
      'pendant-light',
      'oil-lamp',
      'candle-stand',
      'candelabrum',
      'paper-lantern',
      'storm-lantern',
      'jar-lantern',
      'mushroom-lamp',
      'reading-light',
      'task-light',
      'path-light',
      'bollard-light',
      'string-light',
      'beacon-lamp',
      'reflector-lamp',
      'hearth-lamp',
      'sun-catcher',
    ],
  ),
  group(
    'garden-furniture',
    'furnishing',
    'garden',
    'upright',
    'plant, water, or habitat function visible at icon size',
    ['wood', 'stone', 'plant', 'found'],
    'place',
    2,
    [
      'potting-bench',
      'raised-bed',
      'window-box',
      'hanging-planter',
      'herb-rack',
      'seed-tray',
      'compost-bin',
      'rain-barrel',
      'watering-station',
      'hose-reel',
      'garden-cart',
      'wheelbarrow',
      'cold-cloche',
      'propagation-shelf',
      'bee-waterer',
      'butterfly-feeder',
      'bird-feeder',
      'pond-basin',
      'fountain-bowl',
      'plant-ladder',
    ],
  ),
  group(
    'soft-furnishings',
    'furnishing',
    'textile',
    'flat',
    'folds, suspension, and a specific soft use',
    ['plant', 'wood'],
    'place',
    1,
    [
      'quilt-rack',
      'towel-rack',
      'runner-rug',
      'braided-rug',
      'patchwork-rug',
      'wall-tapestry',
      'privacy-curtain',
      'canopy-curtain',
      'hammock',
      'sleeping-roll',
      'pet-blanket',
      'bolster',
      'floor-pillow',
      'window-curtain',
      'picnic-blanket',
    ],
  ),
  group(
    'home-utility',
    'furnishing',
    'utility',
    'upright',
    'a domestic task readable from holders and working height',
    ['wood', 'stone', 'plant', 'found'],
    'place',
    2,
    [
      'wash-basin',
      'mirror-stand',
      'vanity',
      'boot-scraper',
      'mud-tray',
      'key-board',
      'message-board',
      'calendar-board',
      'chalkboard',
      'firewood-rack',
      'log-basket',
      'magazine-rack',
      'book-cart',
      'laundry-hamper',
      'repair-stand',
    ],
  ),
  group(
    'kitchen-furniture',
    'furnishing',
    'kitchen',
    'upright',
    'food storage or preparation geometry without loose clutter',
    ['wood', 'stone', 'plant'],
    'place',
    2,
    [
      'baker-rack',
      'spice-rack',
      'dish-hutch',
      'crock-stand',
      'bread-box',
      'grain-bin',
      'flour-chest',
      'utensil-crock',
      'drying-cabinet',
      'sink-counter',
      'prep-counter',
      'kneading-board',
      'chopping-block',
      'cooling-rack',
      'pie-safe',
    ],
  ),

  group(
    'small-buildings',
    'structure',
    'house',
    'upright',
    'a complete small building with one dominant roofline',
    ['wood', 'stone', 'plant'],
    'place',
    3,
    [
      'garden-cabin',
      'courtyard-house',
      'stilt-house',
      'earth-lodge',
      'roundhouse',
      'a-frame-hut',
      'lean-to-room',
      'sunroom',
      'sleeping-pod',
      'reading-hut',
      'tea-house',
      'gatehouse',
      'caretaker-cottage',
      'lake-cottage',
      'hill-shelter',
      'tool-shed',
      'seed-house',
      'potting-shed',
      'bath-hut',
      'quiet-room',
    ],
  ),
  group(
    'garden-structures',
    'structure',
    'canopy',
    'upright',
    'posts and overhead growth or shade structure',
    ['wood', 'stone', 'plant'],
    'place',
    3,
    [
      'shade-pavilion',
      'vine-pavilion',
      'rose-bower',
      'orchard-arbor',
      'moon-gate',
      'sun-gate',
      'wisteria-walk',
      'covered-walk',
      'garden-colonnade',
      'terrace-canopy',
      'picnic-pavilion',
      'rain-shelter',
      'viewing-deck',
      'pond-deck',
      'tree-platform',
      'green-tunnel',
      'shade-sail',
      'nursery-frame',
      'winter-garden',
      'fern-house',
    ],
  ),
  group(
    'crossings',
    'structure',
    'bridge',
    'long-wide',
    'span, supports, and an obvious crossing path',
    ['wood', 'stone', 'plant'],
    'place',
    3,
    [
      'beam-bridge',
      'arch-bridge',
      'rope-bridge',
      'stepping-bridge',
      'covered-bridge',
      'boardwalk',
      'causeway',
      'ford-platform',
      'canal-crossing',
      'ditch-crossing',
      'switchback-stair',
      'garden-stair',
      'viewing-ramp',
      'jetty',
      'landing-stage',
    ],
  ),
  group(
    'community-places',
    'structure',
    'pavilion',
    'wide',
    'a social focal point with a clear gathering purpose',
    ['wood', 'stone', 'plant', 'found'],
    'place',
    3,
    [
      'meeting-pavilion',
      'story-circle',
      'outdoor-classroom',
      'picnic-hall',
      'tea-pavilion',
      'music-pavilion',
      'dance-platform',
      'market-shelter',
      'repair-commons',
      'tool-library',
      'seed-exchange',
      'trail-kiosk',
      'welcome-gate',
      'rest-station',
      'observation-hide',
    ],
  ),
  group(
    'work-structures',
    'structure',
    'workshop',
    'wide',
    'large working opening plus a specific process',
    ['wood', 'stone', 'found'],
    'place',
    3,
    [
      'carpentry-shop',
      'pottery-shed',
      'weaving-house',
      'repair-bay',
      'wash-house',
      'drying-house',
      'smoke-free-kiln',
      'watermill',
      'windmill-house',
      'pump-house',
      'boathouse',
      'storage-barn',
      'granary',
      'compost-house',
      'glasshouse',
    ],
  ),
  group(
    'landmarks',
    'structure',
    'tower',
    'tall',
    'a singular skyline shape and destination function',
    ['wood', 'stone', 'found'],
    'place',
    3,
    [
      'clocktower',
      'bell-tower',
      'lookout-tower',
      'water-tower',
      'weather-station',
      'observatory',
      'signal-mast',
      'wind-sculpture',
      'memory-monument',
      'wayfinding-spire',
    ],
  ),

  group(
    'datou-rest',
    'datou',
    'pet-rest',
    'low-wide',
    'robot-scale support for a specific resting pose',
    ['wood', 'stone', 'plant'],
    'place',
    1,
    [
      'curl-bed',
      'chin-rest',
      'cooling-pad',
      'warming-mat',
      'window-nook',
      'charging-nest',
      'rain-nook',
      'sun-patch-bed',
      'travel-bed',
      'quiet-cradle',
    ],
  ),
  group(
    'datou-play',
    'datou',
    'pet-play',
    'compact',
    'a clear chase, nudge, balance, or puzzle action',
    ['wood', 'stone', 'plant', 'found'],
    'place',
    2,
    [
      'treat-puzzle',
      'scent-box',
      'nose-target',
      'paw-button',
      'rolling-drum',
      'wobble-board',
      'balance-beam',
      'weave-poles',
      'jump-hoop',
      'crawl-tube',
      'fetch-launcher',
      'tug-post',
      'spin-wheel',
      'bell-target',
      'hide-and-seek-box',
    ],
  ),
  group(
    'datou-care',
    'datou',
    'pet-care',
    'upright',
    'care access sized for Datou’s body and arm',
    ['wood', 'stone', 'plant', 'found'],
    'place',
    2,
    [
      'grooming-stand',
      'paw-wash',
      'drying-station',
      'inspection-ramp',
      'brush-rack',
      'towel-warmer',
      'water-dispenser',
      'snack-drawer',
      'gear-stand',
      'visor-cleaner',
    ],
  ),
  group(
    'datou-explore',
    'datou',
    'pet-course',
    'long-wide',
    'a route choice or sensing challenge',
    ['wood', 'stone', 'plant', 'found'],
    'place',
    2,
    [
      'scent-gate',
      'texture-path',
      'sound-post',
      'light-marker',
      'trail-beacon',
      'sniffing-wall',
      'lookout-step',
      'choice-gate',
      'memory-route',
      'discovery-dock',
    ],
  ),

  group(
    'memory-keepsakes',
    'keepsake',
    'memory',
    'upright',
    'one protected focal memory with a specific display mechanism',
    ['wood', 'stone', 'plant', 'found'],
    'place',
    2,
    [
      'memory-album',
      'shadow-box',
      'memory-diorama',
      'postcard-carousel',
      'photo-cube',
      'story-scroll',
      'route-map',
      'pawprint-plaque',
      'date-marker',
      'memory-jar',
      'ticket-frame',
      'pressed-leaf-book',
      'milestone-board',
      'shared-journal',
      'memory-lantern',
    ],
  ),
  group(
    'sound-keepsakes',
    'keepsake',
    'sound',
    'compact',
    'visible parts that explain a gentle sound',
    ['wood', 'stone', 'plant', 'found'],
    'place',
    2,
    [
      'music-box',
      'thumb-piano',
      'rain-stick',
      'tone-stones',
      'bell-tree',
      'whistle-post',
      'reed-organ',
      'drum-box',
      'echo-tube',
      'song-wheel',
    ],
  ),
  group(
    'display-keepsakes',
    'keepsake',
    'display',
    'upright',
    'a singular object presented with deliberate negative space',
    ['wood', 'stone', 'plant', 'found'],
    'place',
    2,
    [
      'specimen-dome',
      'shell-stand',
      'feather-stand',
      'stone-pedestal',
      'flower-press',
      'curio-cabinet',
      'miniature-stage',
      'trophy-shelf',
      'discovery-mobile',
      'keepsake-tree',
    ],
  ),
  group(
    'seasonal-keepsakes',
    'keepsake',
    'seasonal',
    'compact',
    'seasonal motion or ritual without relying on color alone',
    ['wood', 'stone', 'plant', 'found'],
    'place',
    2,
    [
      'spring-crown',
      'summer-fan',
      'autumn-wheel',
      'winter-star',
      'rain-day-marker',
      'fog-bell',
      'sun-disc',
      'moon-calendar',
      'first-snow-globe',
      'harvest-wreath',
    ],
  ),

  group(
    'garden-tools',
    'tool',
    'hand-tool',
    'long-thin',
    'working head and hand grip clearly communicate the task',
    ['wood', 'stone', 'found'],
    'place',
    2,
    [
      'hand-fork',
      'dibber',
      'soil-rake',
      'leaf-rake',
      'weeding-hook',
      'bulb-planter',
      'watering-wand',
      'pruning-knife',
      'garden-sieve',
      'seed-scoop',
    ],
  ),
  group(
    'craft-tools',
    'tool',
    'bench-tool',
    'compact',
    'a stable working face, guide, or clamp',
    ['wood', 'stone', 'found'],
    'place',
    2,
    [
      'mallet',
      'hand-saw',
      'brace-drill',
      'clamp',
      'wood-plane',
      'chisel',
      'awl',
      'spokeshave',
      'measuring-square',
      'marking-gauge',
    ],
  ),
  group(
    'observation-tools',
    'tool',
    'instrument',
    'compact',
    'lens, dial, pointer, or sample chamber explains observation',
    ['wood', 'stone', 'plant', 'found'],
    'place',
    2,
    [
      'magnifier',
      'periscope',
      'viewing-scope',
      'weather-vane',
      'rain-gauge',
      'wind-meter',
      'sun-dial',
      'soil-tester',
      'sound-funnel',
      'specimen-viewer',
    ],
  ),
] as const satisfies readonly IdentityGroup[];

export type CatalogFormId = (typeof GROUPS)[number]['ids'][number];

export const CATALOG_FORMS: Readonly<Record<CatalogFormId, Form>> = buildCatalog();

export const CATALOG_GROUPS = GROUPS;

function buildCatalog(): Record<CatalogFormId, Form> {
  const out: Partial<Record<CatalogFormId, Form>> = {};
  let ordinal = 0;
  for (const group of GROUPS) {
    for (const id of group.ids) {
      out[id as CatalogFormId] = {
        family: group.family,
        accepts: group.accepts,
        use: group.use,
        tier: group.tier,
        rarity: rarityFor(ordinal++, group.tier),
        sizes: group.silhouette !== 'joint' && group.silhouette !== 'binding',
        finishes: group.family !== 'component',
        identity: identityFor(id, group),
      };
    }
  }
  return out as Record<CatalogFormId, Form>;
}

function identityFor(id: string, group: IdentityGroup): FormIdentity {
  const name = id.replaceAll('-', ' ');
  const lastWord = name.split(' ').at(-1) ?? name;
  return {
    name,
    silhouette: group.silhouette,
    proportions: group.proportions,
    functionalCue: `${group.cue}; it must read immediately as a ${name}`,
    signatureFeatures: [
      `${name} primary geometry`,
      `${lastWord} specific working detail`,
      `one quiet asymmetrical feature unique to the ${name}`,
    ],
    duplicateGroup: group.key,
  };
}

function rarityFor(index: number, tier: Form['tier']): ItemRarity {
  if (index % 47 === 0) return 'legendary';
  if (index % 17 === 0) return 'epic';
  if (index % 7 === 0 || tier === 3) return 'rare';
  if (index % 3 === 0 || tier === 2) return 'uncommon';
  return 'common';
}

function group<const Ids extends readonly string[]>(
  key: string,
  family: FormFamily,
  silhouette: IdentitySilhouette,
  proportions: FormIdentity['proportions'],
  cue: string,
  accepts: Form['accepts'],
  use: FormUse,
  tier: Form['tier'],
  ids: Ids,
): IdentityGroup & { readonly ids: Ids } {
  return { key, family, silhouette, proportions, cue, accepts, use, tier, ids };
}
