import {
  buildBigOak,
  buildBench,
  buildBridge,
  buildFallenLog,
  buildFountain,
  buildLamppost,
  buildMushroom,
  buildSignpost,
  buildBirdbath,
  fernGeometry,
  grassGeometry,
  lilyPadGeometry,
  pineGeometry,
  reedGeometry,
  rockGeometry,
  shrubGeometry,
} from '../props';
import type { ItemKind } from './types';
import type { Verb } from './verbs';

/**
 * The park's original 13 hand-built procedural props, re-expressed as catalog
 * ItemKinds (Phase 2). This is pure registration — the geometry/Group factories
 * in props.ts are unchanged and produce identical output; the catalog simply
 * gives them a uniform interface alongside the downloaded GLB kinds.
 *
 * Footprint radii mirror PROP_COLLIDER + landmark colliderRadius in World.ts so
 * the catalog agrees with the existing collision source of truth.
 */

const V = (...vs: Verb[]): ReadonlySet<Verb> => new Set(vs);
const NONE: ReadonlySet<Verb> = new Set();

export const PROCEDURAL_KINDS: ItemKind[] = [
  // --- scattered foliage (instanced) ---
  {
    id: 'pine',
    name: 'Pine tree',
    category: 'tree',
    mesh: { kind: 'procedural', build: pineGeometry },
    footprintRadius: 0.45,
    blocking: true,
    interactable: false,
    verbs: NONE,
    zones: ['woods', 'grove'],
    spawnWeight: 1,
    scaleRange: [0.8, 1.5],
    license: 'procedural',
  },
  {
    id: 'grass-tuft',
    name: 'Tall grass',
    category: 'grass',
    mesh: { kind: 'procedural', build: grassGeometry },
    footprintRadius: 0,
    blocking: false,
    interactable: true,
    verbs: V('sniff'),
    zones: [],
    spawnWeight: 8,
    scaleRange: [0.8, 1.9],
    license: 'procedural',
  },
  {
    id: 'fern',
    name: 'Fern',
    category: 'fern',
    mesh: { kind: 'procedural', build: fernGeometry },
    footprintRadius: 0,
    blocking: false,
    interactable: true,
    verbs: V('sniff'),
    zones: ['woods'],
    spawnWeight: 3,
    scaleRange: [0.8, 1.9],
    license: 'procedural',
  },
  {
    id: 'reed',
    name: 'Reed cluster',
    category: 'water',
    mesh: { kind: 'procedural', build: reedGeometry },
    footprintRadius: 0.3,
    blocking: true,
    minorCollider: true,
    interactable: true,
    verbs: V('knockOver', 'sniff'),
    zones: ['lake'],
    spawnWeight: 2,
    scaleRange: [0.7, 1.3],
    license: 'procedural',
  },
  {
    id: 'rock',
    name: 'Boulder',
    category: 'rock',
    mesh: { kind: 'procedural', build: rockGeometry },
    footprintRadius: 0.5,
    blocking: true,
    interactable: false,
    verbs: NONE,
    zones: [],
    spawnWeight: 1.5,
    scaleRange: [0.5, 1.8],
    license: 'procedural',
  },
  {
    id: 'shrub',
    name: 'Flowering shrub',
    category: 'shrub',
    mesh: { kind: 'procedural', build: shrubGeometry },
    footprintRadius: 0,
    blocking: false,
    interactable: true,
    verbs: V('sniff'),
    zones: [],
    spawnWeight: 2,
    scaleRange: [0.7, 1.6],
    license: 'procedural',
  },
  {
    id: 'lily-pad',
    name: 'Lily pad',
    category: 'water',
    mesh: { kind: 'procedural', build: lilyPadGeometry },
    footprintRadius: 0,
    blocking: false,
    interactable: false,
    verbs: NONE,
    zones: ['lake'],
    spawnWeight: 1,
    scaleRange: [0.7, 1.4],
    license: 'procedural',
  },

  // --- hero / one-off Groups ---
  {
    id: 'big-oak',
    name: 'Big Oak',
    category: 'tree',
    mesh: { kind: 'procedural-group', build: buildBigOak },
    footprintRadius: 1.6,
    blocking: true,
    interactable: false,
    verbs: NONE,
    zones: ['woods'],
    spawnWeight: 0, // landmark, hand-placed — not auto-scattered
    scaleRange: [1, 1],
    license: 'procedural',
  },
  {
    id: 'bench',
    name: 'Lookout Bench',
    category: 'infrastructure',
    mesh: { kind: 'procedural-group', build: buildBench },
    footprintRadius: 0.6,
    blocking: true,
    interactable: false,
    verbs: NONE,
    zones: ['grove'],
    spawnWeight: 0,
    scaleRange: [1, 1],
    license: 'procedural',
  },
  {
    id: 'fountain',
    name: 'Fountain',
    category: 'infrastructure',
    mesh: { kind: 'procedural-group', build: buildFountain },
    footprintRadius: 1.1,
    blocking: true,
    interactable: false,
    verbs: NONE,
    zones: ['meadow'],
    spawnWeight: 0,
    scaleRange: [1, 1],
    license: 'procedural',
  },
  {
    id: 'bridge',
    name: 'Bridge',
    category: 'infrastructure',
    mesh: { kind: 'procedural-group', build: () => buildBridge() },
    footprintRadius: 0,
    blocking: false,
    interactable: false,
    verbs: NONE,
    zones: ['lake'],
    spawnWeight: 0,
    scaleRange: [1, 1],
    license: 'procedural',
  },
  {
    id: 'mushroom',
    name: 'Toadstool cluster',
    category: 'mushroom',
    mesh: { kind: 'procedural-group', build: buildMushroom },
    footprintRadius: 0.28,
    blocking: true,
    minorCollider: true,
    interactable: true,
    verbs: V('sniff', 'breakScatter'),
    zones: ['woods'],
    spawnWeight: 1,
    scaleRange: [1, 1],
    license: 'procedural',
  },
  {
    id: 'fallen-log',
    name: 'Fallen log',
    category: 'log',
    mesh: { kind: 'procedural-group', build: buildFallenLog },
    footprintRadius: 1.1,
    blocking: true,
    interactable: false,
    verbs: NONE,
    zones: ['woods', 'grove'],
    spawnWeight: 0.5,
    scaleRange: [0.8, 1.2],
    license: 'procedural',
  },
  {
    id: 'lamppost',
    name: 'Lamppost',
    category: 'infrastructure',
    mesh: { kind: 'procedural-group', build: buildLamppost },
    footprintRadius: 0.22,
    blocking: true,
    interactable: false,
    verbs: NONE,
    zones: [],
    spawnWeight: 0, // placed along trails, not random-scattered
    scaleRange: [1, 1],
    license: 'procedural',
  },
  {
    id: 'signpost',
    name: 'Signpost',
    category: 'infrastructure',
    mesh: { kind: 'procedural-group', build: buildSignpost },
    footprintRadius: 0.25,
    blocking: true,
    interactable: false,
    verbs: NONE,
    zones: [],
    spawnWeight: 0,
    scaleRange: [1, 1],
    license: 'procedural',
  },
  {
    id: 'birdbath',
    name: 'Birdbath',
    category: 'infrastructure',
    mesh: { kind: 'procedural-group', build: buildBirdbath },
    footprintRadius: 0.55,
    blocking: true,
    interactable: false,
    verbs: NONE,
    zones: [],
    spawnWeight: 0,
    scaleRange: [1, 1],
    license: 'procedural',
  },
];
